version: '3.7'
services:
  achat-db:
    container_name: achat-db
    image: mysql:8.0
    networks:
      - my-network
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_URL=jdbc:mysql://192.168.3.18:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
  my-app:
    build:
      context: .
    container_name: achat-app
    image: firasar/achat
    ports:
      - '8082:8082'
    networks:
      - my-network
    depends_on:
      - achat-db
    environment:
      - DB_HOST= 192.168.3.18
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DATABASE=
      - DB_PORT=3306
networks:
  my-network:
    name: my-network
volumes:
  dbvol:
