version: '3.7'
services:
        my-db:
                container_name: my-db
                image: mysql:8.0
                networks:
                        - my-network
                environment:
                        - MYSQL_USER=my-db
                        - MYSQL_PASSWORD=admin
                        - MYSQL_DATABASE=achatdb
                        - MYSQL_ROOT_PASSWORD=secret
                volumes:
                        - dbvol:/var/lib/mysql
                ports:
                        - '3306:3306'
                restart: always
        achat-app:
                build:
                        context: .
                container_name: spring-boot-docker-container
                image: fouadk1/achat
                ports:
                        - '8082:8082'
                networks:
                        - my-network
                depends_on:
                        - my-db
                environment:
                        - MYSQL_HOST=my-db
                        - MYSQL_USERNAME=admin
                        - MYSQL_PASSWORD=password
                        - MYSQL_DATABASE=achatdb
                        - MYSQL_PORT=3306
                        - SPRING_DATASOURCE_URL=jdbc:mysql://172.23.240.2:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

networks:
        my-network:
                name: my-network
volumes:
        dbvol:
