version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.6'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=achatdb
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    volumes:
      - 'Database_Volume: /opt/Mysql/data'
  springboot-docker-container:
    container_name: my-spring
    image: firasar/achat
    ports:
      - "8082:8082"
    environment:
      DB_HOST: "192.168.3.18"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone
volumes:
  Database_Volume: