# version: '3.7'
# services:
#   my-db:
#     container_name: my-db
#     image: mysql:8.0
#     networks:
#       - my-network
#     environment:
#       - MYSQL_USER=my-db
#       - MYSQL_PASSWORD=password
#       - MYSQL_DATABASE=appdb
#       - MYSQL_ROOT_PASSWORD=secret
#     volumes:
#       - dbvol:/var/lib/mysql
#     ports:
#       - '3306:3306'
#     restart: always

#   my-app:
#     build:
#       context: .
#     container_name: my-spring
#     image: sofienembk/achat:latest
#     ports:
#       - '8083:8083'
#     networks:
#       - my-network
#     depends_on:
#       - my-db
#     environment:
#       - MYSQL_HOST=localhost
#       - MYSQL_USERNAME=myuser
#       - MYSQL_PASSWORD=password
#       - MYSQL_DATABASE=appdb
#       - MYSQL_PORT=3306
# networks:
#   my-network:
#     name: my-network
# volumes:
#   dbvol:

version: '3.7'
services:
  mysql-standalone:
    image: 'mysql:5.6'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
    ports:
      - '3306:3306'
  springboot-docker-container:
    build:
      context: .
    container_name: spring-boot-docker-container
    image: sofienembk/achat
    ports:
      - '8083:8083'
    depends_on:
      - mysql-standalone
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/mydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: 'myuser'
      SPRING_DATASOURCE_PASSWORD: 'password'
volumes:
  dbvol:
